name: Fetch images from Gmail


on:
schedule:
- cron: '*/15 * * * *' # every 15 minutes
workflow_dispatch:


permissions:
contents: write


jobs:
fetch:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4


- name: Set up Python
- uses: actions/setup-python@v5
with:
python-version: '3.x'


- name: Install deps
run: |
python -m pip install --upgrade pip


- name: Fetch attachments from Gmail
env:
GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
GMAIL_IMAP_LABEL: ${{ secrets.GMAIL_IMAP_LABEL }}
run: |
python scripts/fetch_attachments.py


- name: Commit & push if changes
run: |
git config user.name "${{ secrets.COMMIT_AUTHOR_NAME || 'github-actions' }}"
git config user.email "${{ secrets.COMMIT_AUTHOR_EMAIL || 'actions@users.noreply.github.com' }}"
git add images || true
if ! git diff --cached --quiet; then
git commit -m "Add images from Gmail"
git push
else
echo "No new images to commit."
fi
